language: node_js
node_js:
- '5'
services:
- mongodb
addons:
  code_climate:
    repo_token: "eeb4646ca63a0e2da1681e327918168e216fa59cbaa9c5cfaf808dec0778892b"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: aBBQ6eDlodTtGH9qcqHrUitYP9E5IYPZbZThqoncuf45B5yzKlBOK/KahRE+8rDZ/pQu4SGUXhKX17EluGxnJ59UUgIAey28mAvU/ao2MUgzB/kmnUfRQsGF+Ruj7I3Doo9F8V7OrpVMQuyzuKKUQjuu4cvq0XOn8rEmHLNBwgK/PjPfZ+g9GwdcBsluHex8+YnWv6kfm7ZCYSWRSd4MeVyBXf5ja+1Gf3+Eds0D71x2azedw+UBCPdPfMKlBPE7G0X2yj0MclOicP/12lN8inV/VZMHfXQVdppF4GjZSQXn+2MSZ6NuEChzuWkUejA7G/Vg6GekxeP49Bim46fY3CU0HWreQEjqkCTK2BQaye7oN9NnwjAwk9XRGQaQTc86D5vBHhycrPP9LKeQ8p/yaaPgw5gkaWSr74VC85oUPpR3sZehhp2C7HKayPlNPxd+d6fvyRxFzGTiuLqwG0Eg8KUrd5VL+XgH1PP3qtfTx+ul9eYpj2egyeveFybOV/K8G/GHUrJAPGTSizXSrqqfJApY8J+In+ToTVZ8V+okdwpsZVcwq2srlr5W8vesbjElbjtWPY/moyobu1yBsrWmHKcIdxzUpdWlPyudlsFJMAlEnMxjjf6PWqLslMR5uJ1q1skgo69PDhtu9EF+R0L9DG0qB+dsM1TmzotmfiicXcc=
  on:
    tags: true
    branches: true
